services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
      - ./aligner:/app/aligner
      - ./data:/app/data
      - ./models:/app/models
      - ./submissions:/app/submissions
    ports:
      - "8000:8000"
    
    deploy:
      mode: replicated
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
