name: krypto
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - asttokens=3.0.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - coloredlogs=15.0.1
  - comm=0.2.2
  - cuda-cudart=12.8.57
  - cuda-nvrtc=12.8.61
  - cuda-version=12.8
  - cudnn=9.7.1.26
  - debugpy=1.8.12
  - decorator=5.2.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - gmp=6.3.0
  - gmpy2=2.2.1
  - humanfriendly=10.0
  - importlib-metadata=8.6.1
  - intel-openmp=2022.0.1
  - ipykernel=6.29.5
  - ipython=9.0.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - libabseil=20240116.2
  - libedit=3.1.20230828
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgcc=14.2.0
  - libprotobuf=4.25.3
  - libsodium=1.0.20
  - libstdcxx=14.2.0
  - llvm-openmp=19.1.7
  - matplotlib-inline=0.1.7
  - mkl=2023.2.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - conda-forge::onnxruntime
  - openssl=3.4.1
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.50
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.12.2
  - python-dateutil=2.9.0.post0
  - python-flatbuffers=24.3.25
  - python_abi=3.12
  - pyzmq=26.2.1
  - readline=8.2
  - six=1.17.0
  - sqlite=3.49.1
  - stack_data=0.6.3
  - tbb=2021.8.0
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - tzdata=2025a
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - pip:
      - antlr4-python3-runtime==4.9.3
      - beautifulsoup4==4.13.3
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - contourpy==1.3.1
      - cycler==0.12.1
      - fonttools==4.56.0
      - gdown==5.2.0
      - huggingface-hub==0.29.1
      - idna==3.10
      - imageio==2.37.0
      - ipywidgets==8.1.5
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - matplotlib==3.10.1
      - numpy==2.2.3
      - omegaconf==2.3.0
      - onnx==1.17.0
      - opencv-python==4.11.0.86
      - protobuf==5.29.3
      - pyparsing==3.2.1
      - pysocks==1.7.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scipy==1.15.2
      - soupsieve==2.6
      - tifffile==2025.2.18
      - timm==1.0.15
      - tokenizers==0.21.0
      - tqdm==4.67.1
      - transformers==4.47.0
      - urllib3==2.3.0
      - widgetsnbextension==4.0.13
      - uvicorn==0.34.0
      - fastapi==0.115.11
      - python-multipart==0.0.20
      - scikit-learn==1.6.1
      - wandb==0.19.8
      - pandas==2.2.3
      - igraph==0.11.8
